[assembly: System.Reflection.AssemblyTitle("NGuard")]
[assembly: System.Reflection.AssemblyDescription("Lightweight guard / pre-condition / parameter validation framework for .NET")]
[assembly: System.Reflection.AssemblyConfiguration("")]
[assembly: System.Reflection.AssemblyCompany("")]
[assembly: System.Reflection.AssemblyProduct("NGuard")]
[assembly: System.Reflection.AssemblyCopyright("Copyright Matthew King 2012")]
[assembly: System.Reflection.AssemblyTrademark("")]
[assembly: System.Reflection.AssemblyCulture("")]
[assembly: System.Resources.NeutralResourcesLanguage("en")]
[assembly: System.Reflection.AssemblyVersion("1.0.0.0")]
[assembly: System.Reflection.AssemblyFileVersion("1.0.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersion("1.0.0")]
